### ISSUE TITLE
GL6_FACE.DAT To-Do

### ISSUE THREAD

**Issue by Risae** [Risae/Growlanser-6-English-Translation#2]
- [X] `00000144.FACE` Warslee, Rio Rey, PMB HQ Title card: 
- [ ] `00000145.FACE` Totuwa. Juwaina, Felmentia Title card: 
- [ ] `00000146.FACE` Zaramba, Zerdok, Geilenach Title card: 
- [ ] `00000147.FACE` Jaergen, XXX, Pothrad Village Title card: 
- [ ] `00000148.FACE` Transgate Center, XXX, XXX Title card: 
- [ ] `00000149.FACE` Makinus, Dastis, Dragonpit Tower Title card: 
- [ ] `00000150.FACE` Schizarz, Leystan, Jian Mountain. El Hingis, Hingistan Title card: 
- [ ] `00000151.FACE` Jian Mountain, Fomeros, Royferon Title card: 
- [ ] `00000152.FACE` XXX, Transgate Center, XXX Title card: 
- [ ] `00000232.FACE` Goatland Worldmap: https://i.imgur.com/dJiuJ7v.png
- [ ] `00000233.FACE` Esgrentz Worldmap: https://i.imgur.com/lbmzHlA.png
