### ISSUE TITLE
GL6_FILE.DAT To-Do

### ISSUE THREAD

**Issue by Risae** [Risae/Growlanser-6-English-Translation#4]
- [ ] `00000566.mss` Switch around the spell casting text
- [ ] `00000569.mss` Increase the size of the "Treasure Scout" textbox
- [ ] `00000573.mss` Switch around the buying/selling text
- [ ] `00000594.mss` Switch around the equipment change text
- [ ] `00000596.mss` Increase the textbox size of KP
- [ ] `00000602.tm2` GL6 Icons
- [ ] `00000604.tm2` Character Menu
- [ ] `00000606.tm2` Mission complete screen
- [ ] `00000608.tm2` Prologue stats screen
- [ ] `00000611.tm2` Yurii Main Menu
- [ ] `00000612.tm2` Friend rating screen
- [ ] `00000647.tm2` Gem creating screen
- [ ] `00000803.dat` Additional Plate info text
- [ ] `00000806.dat` Yurii Attributes
