### ISSUE TITLE
GL6_MOV.DAT To-Do

### ISSUE THREAD

**Issue by Risae** [Risae/Growlanser-6-English-Translation#5]
#### Subtitle the ingame movies

- [ ] `00000006.MOVIE` Event - The ground shakes from the explosion
- [ ] `00000007.MOVIE` Event - Spaceship surfacing
- [ ] `00000009.MOVIE` End - Common Ending
- [ ] `00000010.MOVIE` End - Wendy
- [ ] `00000011.MOVIE` End - Rukias
- [ ] `00000012.MOVIE` End - Iristelessa
- [ ] `00000013.MOVIE` End - Anita
- [ ] `00000014.MOVIE` End - Hofman
- [ ] `00000015.MOVIE` End - Haschen
- [ ] `00000016.MOVIE` End - Yurii
- [ ] `00000017.MOVIE` End - Neilis
- [ ] `00000018.MOVIE` Event - Admonisher Explanation
